FROM openjdk:11

ENV SBT_VERSION 1.3.0

RUN \
  curl -L -o sbt-$SBT_VERSION.deb http://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb && \
  dpkg -i sbt-$SBT_VERSION.deb && \
  rm sbt-$SBT_VERSION.deb && \
  apt-get update && \
  apt-get install sbt && \
  sbt sbtVersion

# (sbt sbtVersion will force the fetching of the right sbt jar needed)

WORKDIR /root/project
