#!/bin/bash

cd $(dirname $0)

ENABLE_TTY=${ENABLE_TTY:--t}
IMAGE="code-retreat-python-env"
VERSION="1"
TAG="$IMAGE:$VERSION"

docker images | grep -q "$IMAGE[ ]*$VERSION" || docker build -t $TAG .

docker run --rm -i ${ENABLE_TTY} \
  -u $(id -u):$(id -g) \
  -v $(pwd):/tmp/project:rw \
  -w /tmp/project \
  $TAG $@