#!/bin/bash

cd $(dirname $0)

ENABLE_TTY=${ENABLE_TTY:--t}

mkdir -p docker-home && touch docker-home/empty_file || exit 1

docker run --rm -i ${ENABLE_TTY} \
  -u $(id -u):$(id -g) \
  -v $(pwd):/tmp/project:rw \
  -v $(pwd)/docker-home:/tmp/docker-home:rw \
  -w /tmp/project \
  -e HOME=/tmp/docker-home \
  -e GEM_HOME=/tmp/docker-home/gem \
  -e BUNDLE_PATH=/tmp/docker-home/bundle \
  ruby:2.5-alpine sh -c "$@"
