#!/usr/bin/env bash

# Test and Commit or Revert

# inspirations:
# https://medium.com/@kentbeck_7670/test-commit-revert-870bbd756864

./scripts/test && git add -A && git commit -a -m "tests pass, code works" || git reset --hard && git clean -f
